### ISSUE TITLE
Error multiple queries

### ISSUE THREAD

**Issue by fabianosfbr** [saloonphp/xml-wrangler#20]
I try run and works fine
$el = $xmlReader->value('infNFe.det.2')->sole();
Result

![image](https://github.com/saloonphp/xml-wrangler/assets/4691302/fb5108c7-01a0-4575-bc32-73a47b6d94d3)

But a try multiple queries and give error

 $el = $xmlReader->value('infNFe.det.2.prod')->sole();

![image](https://github.com/saloonphp/xml-wrangler/assets/4691302/ee5d374a-0286-4b25-a151-e13c5a6e2825)

**Comment by Sammyjo20** [comment]
Hey @fabianosfbr thanks for reporting this - just so I can get a bit more info...

- What version of XML Wrangler are you using?
- What reader are you using? E.g `Reader::fromString()` or `Reader::fromStream()` etc

When you say "try multiple queries and give error" do you mean making multiple searches like this?

```php
$reader->value('infNFe.det.2')->sole(); // Works

// And then

$reader->value('infNFe.det.2.prod')->sole(); // Falls over?
```

**Comment by Sammyjo20** [comment]
Hey @fabianosfbr I'm going to close this issue for now - please feel free to re-open if you are still having this issue.
