### ISSUE TITLE
How can I chain write with the XML writer?

### ISSUE THREAD

**Issue by chatsikm** [saloonphp/xml-wrangler#27]
Greetings, since there is no Discussions tab, I am obliged to ask my question via an Issue.

My question is, is there a way to write via chain ?

For example

```php
$writer = new XMLWriter();

$writer->write('root', 'customElement' => myElement];

// .... more code

$writer->write('root', 'customElement2' => myElement2);

// ... more code

$writer->gerenate
```

**Comment by Sammyjo20** [comment]
Hey @chatsikm thanks for your question! Yes the writer does currently support this. You can write multiple times with one instance but you can't partially write something, and then write the rest currently.
