### ISSUE TITLE
Is there a way we can loop through the nodes without loading all elements

### ISSUE THREAD

**Issue by rajeev-k-tomy** [saloonphp/xml-wrangler#33]
First of all, this is an awesome package. The `values()` and `elements()` methods are handy to retrieve all the data of the xml file.

However, I want to parse large xml files and I dont want to load everything into array. Instead, i want to loop over each node. Is that possible with this package?

**Comment by Sammyjo20** [comment]
Yes, that is what the singular `value` and `element` methods are for. Please see the documentation: 

https://github.com/saloonphp/xml-wrangler?tab=readme-ov-file#reading-specific-values

**Comment by rajeev-k-tomy** [comment]
@Sammyjo20 Thank you for your reply. But, we need to know about the content of the xml in order to use `value` or `element`. I need to loop through the content from top to bottom without loading all (so that i can save memory usage) and without providing any relevant "name" or "value".
